# .github/workflows/android.yml
name: Android CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install NDK & Rust targets
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip libstdc++-static
          rustup target add aarch64-linux-android
          cargo install cargo-ndk
      - name: Build Rust FFI libs
        run: |
          cargo ndk -t arm64-v8a -o android/app/src/main/jniLibs build --release
      - name: Build APK
        run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
